// video-list-vuejs-typescript/src/App.vue
<template>
  <h1>Media List</h1>
  <MediaList :videos="mockData" />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import MediaList from "@/components/MediaList.vue";
import { mockData } from "@/data/mockData";

export default defineComponent({
  name: "App",
  components: {
    MediaList: MediaList,
  },
  computed: {
    mockData: () => mockData,
  },
});
</script>

// video-list-angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {mockData} from "../data/mockData";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  readonly mockData = mockData;
}

<h1>Video List</h1>
<app-video-list [videos]="mockData"></app-video-list>
