// video-list-angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {mockData} from "../data/mockData";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  readonly mockData = mockData;
}

<h1>Video List</h1>
<app-video-list [videos]="mockData"></app-video-list>

// video-list-vuejs/src/App.vue
<template>
  <h1>Media List</h1>
  <MediaList :videos="mockData" />
</template>

<script>
import MediaList from "./components/MediaList";
import {mockData} from "./data/mockData";

export default {
  name: "App",
  components: {
    MediaList
  },
  created() {
    this.mockData = mockData;
  }
}
</script>
